language: python

install:
  - pip install tox
  - pip install -e .

script: tox -e $TOXENV

matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=flake8
